/**
 * Regenerates docs/ADMIN_CAPABILITY_MATRIX.md from the code
 * (§ CAPABILITY MATRIX). Run: `npm run audit:capabilities`.
 *
 * Every API method (auth, permissions, audit entry, first backend call, UI
 * callers, roles that hold it) and every admin page gate. Static reading of
 * the source: it reports what the code says. Don't edit the output by hand.
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { readRoutes, type RouteMethod } from '../../lib/audit/routeInventory';
import { ROLE_TEMPLATES } from '../../lib/auth/permissions';

const ROOT = process.cwd();

function walk(dir: string, match: (name: string) => boolean, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name.startsWith('.')) continue;
    const path = join(dir, name);
    if (statSync(path).isDirectory()) walk(path, match, out);
    else if (match(name)) out.push(path);
  }
  return out;
}

const uiFiles = [...walk(join(ROOT, 'components'), (n) => n.endsWith('.tsx')), ...walk(join(ROOT, 'app'), (n) => n.endsWith('.tsx'))].map((file) => ({ file: relative(ROOT, file), text: readFileSync(file, 'utf8') }));

function uiCallers(route: RouteMethod): string[] {
  const pattern = new RegExp(
    route.path
      .split('/')
      .map((part) => (/^\[.+\]$/.test(part) ? "(?:\\$\\{[^}]+\\}|[^/'\"`?]+)" : part.replace(/[.*+?^${}()|\\]/g, '\\$&')))
      .join('/') + "(?:['\"`?]|\\$\\{)",
  );
  return uiFiles.filter(({ text }) => pattern.test(text)).map(({ file }) => file);
}

function rolesFor(permissions: string[]): string {
  if (permissions.length === 0) return '—';
  const holders = ROLE_TEMPLATES.filter((t) => t.key !== 'super_admin' && permissions.some((p) => (t.permissions as readonly string[]).includes(p))).map((t) => t.label);
  return holders.length > 0 ? holders.join('; ') : 'Super admin only';
}

const AUTH_LABEL: Record<string, string> = {
  staff: 'staff session',
  device: 'machine screen credential',
  machine_api: 'machine API (HMAC)',
  owner: 'owner session',
  cron: 'cron / internal secret',
  webhook: 'signed webhook',
  customer: 'customer session',
  creator: 'creator session',
  session_endpoint: 'sign-in endpoint',
  public: '**public**',
};

function status(route: RouteMethod, callers: string[]): string {
  if (!route.auth.includes('staff')) return 'System interface';
  if (route.method === 'GET') return callers.length > 0 ? 'Complete' : 'Read API';
  if (!route.audited) return 'Works, unaudited';
  return callers.length > 0 ? 'Complete' : 'No UI caller';
}

const routes = readRoutes(ROOT);
const rows = routes.map((route) => {
  const callers = uiCallers(route);
  return { route, callers, status: status(route, callers) };
});

const pages = walk(join(ROOT, 'app/admin/(protected)'), (n) => n === 'page.tsx' || n === 'layout.tsx').map((file) => {
  const text = readFileSync(file, 'utf8');
  const gate = text.match(/requireAdminPage\(\s*'([a-z_]+)'\s*,\s*'([a-z_.]+)'\s*\)/);
  const section = text.match(/requireAdminSection\(\s*'([a-z_]+)'\s*\)/);
  const route = '/' + relative(join(ROOT, 'app'), file).replace(/\(protected\)\//, '').replace(/\/(page|layout)\.tsx$/, '');
  return { route, kind: file.endsWith('layout.tsx') ? 'layout' : 'page', gate: gate ? `${gate[2]} (section ${gate[1]})` : section ? `section ${section[1]}` : /requireStaffSession|requireAdminSection|hasPermission/.test(text) ? 'staff session (+ checks inside)' : 'inherits layout' };
});

const counts = new Map<string, number>();
for (const row of rows) counts.set(row.status, (counts.get(row.status) ?? 0) + 1);
const areas = new Map<string, typeof rows>();
for (const row of rows) {
  const area = row.route.path.split('/').slice(0, 4).join('/');
  areas.set(area, [...(areas.get(area) ?? []), row]);
}

const lines: string[] = [];
lines.push('# Admin capability matrix', '');
lines.push('Generated by `scripts/audit/capabilityMatrix.ts` from `app/api/**/route.ts` (per HTTP method) and `app/admin/(protected)/**` (page gates). Regenerate with `npm run audit:capabilities`; don’t edit by hand.', '');
lines.push('Static reading of the source: **Auth** and **Permission** are what each method’s code checks; **Audit** is whether the method writes a central audit entry; **UI** counts `.tsx` files that call the path. `tests/security/routeGuard.test.ts` enforces the same reading: every staff method checks a permission, and only the listed public methods are unauthenticated.', '');
lines.push(`Route methods: **${rows.length}**.`, '');
lines.push('| Status | Methods |', '|---|---:|');
for (const [name, count] of [...counts.entries()].sort((a, b) => b[1] - a[1])) lines.push(`| ${name} | ${count} |`);
lines.push('', '- Complete: a staff method with a UI caller and, for writes, an audit entry.', '- Read API: a staff GET no page calls (pages read the service directly).', '- Works, unaudited: a staff write without a central audit entry (some services keep their own record).', '- No UI caller: an audited staff write whose path wasn’t found in any `.tsx` file. UI code that assembles a path in pieces (`${base}/publish`, `/restock/${id}/${action}`) isn’t matched, so check the row before treating it as missing.', '- System interface: machine, owner, cron, webhook, customer or public.', '');
for (const [area, list] of [...areas.entries()].sort()) {
  lines.push(`## \`${area}\``, '', '| Method | Auth | Permission | Roles | Audit | Backend | UI | Status |', '|---|---|---|---|---|---|---|---|');
  for (const { route, callers, status: s } of list) {
    lines.push(
      `| \`${route.method} ${route.path}\` | ${route.auth.map((a) => AUTH_LABEL[a]).join(', ')} | ${route.permissions.map((p) => `\`${p}\``).join(', ') || '—'} | ${rolesFor(route.permissions)} | ${route.method === 'GET' ? 'n/a' : route.audited ? 'yes' : 'no'} | ${route.backend ? `\`${route.backend}\`` : '—'} | ${callers.length === 0 ? '—' : `${callers[0].replace(/^components\//, 'c/')}${callers.length > 1 ? ` +${callers.length - 1}` : ''}`} | ${s} |`,
    );
  }
  lines.push('');
}
lines.push('## Admin page gates', '', '| Page | Kind | Gate |', '|---|---|---|');
for (const page of pages.sort((a, b) => a.route.localeCompare(b.route))) lines.push(`| \`${page.route}\` | ${page.kind} | ${page.gate} |`);
lines.push('');

writeFileSync(join(ROOT, 'docs/ADMIN_CAPABILITY_MATRIX.md'), lines.join('\n'));
console.log(`Wrote docs/ADMIN_CAPABILITY_MATRIX.md: ${rows.length} route methods, ${pages.length} admin pages/layouts.`);
for (const [name, count] of counts) console.log(`  ${name}: ${count}`);
