import type { AuditFields } from './common';

/**
 * A code that reduces what a customer pays (§ discount codes).
 *
 * Distinct from a referral code, which already exists and does a
 * different job: a referral names a creator, credits them commission,
 * and is generated by the system. A discount code is issued by the
 * business, names nobody, and pays nobody. Conflating them would mean
 * either paying commission on a PR box or inventing a creator to own a
 * launch promo.
 *
 * The demanding case is the one this was asked for: a 100% code for an
 * influencer PR box. That is not a bigger discount, it is a different
 * kind of order — nothing is charged, so there is no M-Pesa prompt to
 * send, no callback to wait for, and no receipt to quote. The checkout
 * has to notice that and settle the order itself rather than asking
 * Daraja to collect zero shillings, which Daraja rejects.
 */
export type DiscountCodeKind = 'percentage' | 'fixed';

export interface DiscountCode extends AuditFields {
  businessId: string;
  /**
   * The code as typed, uppercased. Stored on the document as well as
   * being its id, because the id is the lookup key and this is what
   * gets shown back to staff.
   */
  code: string;
  kind: DiscountCodeKind;
  /**
   * Percent (1-100) for `'percentage'`, whole KES for `'fixed'`.
   *
   * One field rather than two nullable ones: a code is exactly one of
   * the two kinds, and two columns invites a row that is somehow both
   * or neither.
   */
  value: number;
  /**
   * Whether delivery is free too.
   *
   * Separate from the discount itself because a 100% code alone does
   * not produce a free order — the box becomes free and the customer
   * still pays KES 250 to have it delivered. For a PR box sent to an
   * influencer that is not what anybody means by free, and for a
   * promotional code it might be exactly right. So it is a choice.
   */
  waivesDelivery: boolean;
  /**
   * How many times this code may be redeemed in total, or null for
   * unlimited.
   *
   * Counted across every customer, not per customer. A code handed to
   * one influencer is `maxRedemptions: 1`, and the limit has to hold
   * even if they open the checkout twice at once, which is why
   * redemption is a transaction rather than a read-then-write.
   */
  maxRedemptions: number | null;
  /** Redemptions so far. Incremented in the same transaction that checks the limit. */
  redemptionCount: number;
  /** Inclusive start, or null to be live immediately. */
  startsAt: FirebaseFirestore.Timestamp | null;
  /** Exclusive end, or null never to expire. */
  expiresAt: FirebaseFirestore.Timestamp | null;
  /**
   * A switch staff can flip without deleting the record.
   *
   * Deleting a spent code would take its redemption history with it,
   * and that history is the answer to "how did the PR campaign go".
   */
  isActive: boolean;
  /** What this code is for, in staff words: "Influencer PR — @handle", "October launch". Null when nobody wrote one. */
  note: string | null;
}

/** Why a code cannot be used, in a form the checkout can turn into a sentence. */
export type DiscountCodeRejection =
  | 'not_found'
  | 'inactive'
  | 'not_started'
  | 'expired'
  | 'fully_redeemed';

export const DISCOUNT_CODE_MAX_PERCENT = 100;

/** A shape the checkout can price with, whichever kind the code is. */
export interface DiscountCodeEffect {
  code: string;
  kind: DiscountCodeKind;
  value: number;
  /** What comes off the box subtotal, already resolved to whole KES and capped at the subtotal. */
  discountKes: number;
  waivesDelivery: boolean;
}
