// Best-effort town/county classification for each Jumia pickup station
// name in data/jumiaPickupStations.raw.json — used only to make the
// stations searchable/filterable by county and town. This is derived
// from the station's operator+place naming convention (e.g. "Fortify
// Kericho Station" -> Kericho, Kericho County) and general knowledge
// of Kenyan administrative geography, NOT from a verified gazetteer
// or reverse-geocoding of the given coordinates. Where a station name
// carries no identifiable place (e.g. "Fortify Solutions"), or the
// place name is genuinely ambiguous between counties, both `town` and
// `county` are left `null` rather than guessed — deliberately, so a
// wrong-but-confident classification never silently misleads search
// or (eventually) zone-based pricing. Keyed by exact station_name
// from the raw file; a station with no entry here (e.g. the source
// file is updated with new stations later) simply gets `null` back,
// not a crash or a guess.
export const STATION_GEOGRAPHY = {
  'Jumia Kloss Kimathi Street Station': { town: 'Nairobi CBD', county: 'Nairobi' },
  'Fortify Kangemi Station': { town: 'Kangemi', county: 'Nairobi' },
  'Jumia Lakeland Highridge Station': { town: 'Highridge', county: 'Nairobi' },
  'Jumia G4S Wajir Station': { town: 'Wajir', county: 'Wajir' },
  'Jumia Amison Kapenguria Station': { town: 'Kapenguria', county: 'West Pokot' },
  'Jumia Cossim Luanda Station': { town: 'Luanda', county: 'Vihiga' },
  'Jumia Kebian Majengo Station': { town: 'Majengo (Kisumu)', county: 'Kisumu' },
  'Kebian Mbale Station': { town: 'Mbale', county: 'Vihiga' },
  'Jumia G4S Kakuma Station': { town: 'Kakuma', county: 'Turkana' },
  'G4S Lodwar Station': { town: 'Lodwar', county: 'Turkana' },
  'Jumia G4S Lokichar Station': { town: 'Lokichar', county: 'Turkana' },
  'Jumia Amison Kiminini Station': { town: 'Kiminini', county: 'Trans Nzoia' },
  'Jumia Amison Kitale Station': { town: 'Kitale', county: 'Trans Nzoia' },
  'Jumia Lakeland Kitale-Station': { town: 'Kitale', county: 'Trans Nzoia' },
  'Kebian Kitale Station': { town: 'Kitale', county: 'Trans Nzoia' },
  "Jumia Fortify MOIs BRIDGE Station": { town: "Moi's Bridge", county: 'Uasin Gishu' },
  'Jumia JBN Express Chogoria Station': { town: 'Chogoria', county: 'Tharaka-Nithi' },
  'Jumia Skyveshop Chuka Station': { town: 'Chuka', county: 'Tharaka-Nithi' },
  'G4S Hola Station': { town: 'Hola', county: 'Tana River' },
  'Jumia KimCindy Mwatate Station': { town: 'Mwatate', county: 'Taita-Taveta' },
  'G4S Taveta Station': { town: 'Taveta', county: 'Taita-Taveta' },
  'Jumia Voi Station': { town: 'Voi', county: 'Taita-Taveta' },
  'G4S Wundanyi Station': { town: 'Wundanyi', county: 'Taita-Taveta' },
  'Jumia TRD Bondo Station': { town: 'Bondo', county: 'Siaya' },
  'Jumia Kebian Siaya Station': { town: 'Siaya', county: 'Siaya' },
  'Jumia Kebian Ugunja Station': { town: 'Ugunja', county: 'Siaya' },
  'G4S Maralal Station': { town: 'Maralal', county: 'Samburu' },
  'Jumia Flexcom Chaka Station': { town: 'Chaka', county: 'Nyeri' },
  'Jumia Skyveshop Karatina Station': { town: 'Karatina', county: 'Nyeri' },
  'Skyveshop Nyeri Station': { town: 'Nyeri', county: 'Nyeri' },
  'Jumia Skyveshop Othaya Station': { town: 'Othaya', county: 'Nyeri' },
  'G4S Olkalou Station': { town: 'Ol Kalou', county: 'Nyandarua' },
  'Jumia Lakeland Nyamira Station': { town: 'Nyamira', county: 'Nyamira' },
  'G4S Kilgolis Station': { town: 'Kilgoris', county: 'Narok' },
  'Flexcom Narok Station': { town: 'Narok', county: 'Narok' },
  'Fortify Kapsabet Station': { town: 'Kapsabet', county: 'Nandi' },
  'Fortify Nandi Hills Station': { town: 'Nandi Hills', county: 'Nandi' },
  'JBN Express Kenol Station': { town: 'Kenol', county: "Murang'a" },
  'Jumia JBN Express Muranga Station': { town: "Murang'a", county: "Murang'a" },
  'Jumia TRD Awendo Station': { town: 'Awendo', county: 'Migori' },
  'Jumia Flexcom Isebania Station': { town: 'Isebania', county: 'Migori' },
  'Jumia TRD Kehancha Station': { town: 'Kehancha', county: 'Migori' },
  'Flexcom Migori Station': { town: 'Migori', county: 'Migori' },
  'Jumia TRD Rongo Station': { town: 'Rongo', county: 'Migori' },
  'Jumia Skyveshop Makutano Station': { town: 'Makutano (Meru)', county: 'Meru' },
  'G4S Maua Station': { town: 'Maua', county: 'Meru' },
  'Jumia Skyveshop Maua Station': { town: 'Maua', county: 'Meru' },
  'Jumia Flexcom Meru Downtown station': { town: 'Meru', county: 'Meru' },
  'Jumia Flexcom Meru Station': { town: 'Meru', county: 'Meru' },
  'Jumia Skyveshop Nkubu Station': { town: 'Nkubu', county: 'Meru' },
  'Jumia Flexcom Timau Station': { town: 'Timau', county: 'Meru' },
  'Jumia KimCindy Emali Station': { town: 'Emali', county: 'Makueni' },
  'Jumia KimCindy Kibwezi Station': { town: 'Kibwezi', county: 'Makueni' },
  'G4S Mtito Andei Station': { town: 'Mtito Andei', county: 'Makueni' },
  'Jumia Cossim Wote Station': { town: 'Wote', county: 'Makueni' },
  'G4S-Lamu Station': { town: 'Lamu', county: 'Lamu' },
  'Place Kimwa Digital Building': { town: null, county: null },
  'Flexcom Nanyuki Station': { town: 'Nanyuki', county: 'Laikipia' },
  'Jumia TRD Nyahururu Station': { town: 'Nyahururu', county: 'Laikipia' },
  'Flexcom Diani Station': { town: 'Diani', county: 'Kwale' },
  'Jumia Flexcom Kwale Station': { town: 'Kwale', county: 'Kwale' },
  'Jumia Flexcom Lungalunga Station': { town: 'Lunga Lunga', county: 'Kwale' },
  'Jumia Skyveshop Kitui Station': { town: 'Kitui', county: 'Kitui' },
  'Jumia Skyveshop Mwingi Station': { town: 'Mwingi', county: 'Kitui' },
  'Fortify Keroka Station': { town: 'Keroka', county: 'Nyamira' },
  'Cossim Kisii Station': { town: 'Kisii', county: 'Kisii' },
  'Jumia Lakeland Kisii Station': { town: 'Kisii', county: 'Kisii' },
  'G4S Ogembo Station': { town: 'Ogembo', county: 'Kisii' },
  'Jumia Skyveshop Kagio Station': { town: 'Kagio', county: 'Kirinyaga' },
  'Jumia Elegant Kagumo Station': { town: 'Kagumo', county: 'Nyeri' },
  'Jumia Flexcom Kerugoya Station': { town: 'Kerugoya', county: 'Kirinyaga' },
  'Jumia TRD Kutus Station': { town: 'Kutus', county: 'Kirinyaga' },
  'Jumia JBN Express Mwea Station': { town: 'Mwea', county: 'Kirinyaga' },
  'Jumia JBN Sagana Station': { town: 'Sagana', county: 'Kirinyaga' },
  'Jumia Kilifi Station': { town: 'Kilifi', county: 'Kilifi' },
  'Jumia Malindi Station': { town: 'Malindi', county: 'Kilifi' },
  'Skyveshop Mazeras Station': { town: 'Mazeras', county: 'Kilifi' },
  'Jumia Vipingo Station': { town: 'Vipingo', county: 'Kilifi' },
  'Jumia Watamu Station': { town: 'Watamu', county: 'Kilifi' },
  'Fortify Kericho Station': { town: 'Kericho', county: 'Kericho' },
  'Jumia Mariakani Station': { town: 'Mariakani', county: 'Kilifi' },
  'Red Sea service station': { town: null, county: null },
  'Cossim Kakamega Station': { town: 'Kakamega', county: 'Kakamega' },
  'Fortify Kakamega Station': { town: 'Kakamega', county: 'Kakamega' },
  'Kebian Mumias Station': { town: 'Mumias', county: 'Kakamega' },
  'Jumia Amison Sabatia Station': { town: 'Sabatia', county: 'Vihiga' },
  'Jumia Flexcom Isiolo Station': { town: 'Isiolo', county: 'Isiolo' },
  'Cossim Homabay Station': { town: 'Homa Bay', county: 'Homa Bay' },
  'Jumia Cossim Mbita Station': { town: 'Mbita', county: 'Homa Bay' },
  'Jumia Cossim Oyugis Station': { town: 'Oyugis', county: 'Homa Bay' },
  'Skyveshop Embu Station': { town: 'Embu', county: 'Embu' },
  'G4S Iten Station': { town: 'Iten', county: 'Elgeyo-Marakwet' },
  'Jumia Amison Malaba Station': { town: 'Malaba', county: 'Busia' },
  'Jumia Amison Kimilili Station': { town: 'Kimilili', county: 'Bungoma' },
  'Jumia Amison Webuye Station': { town: 'Webuye', county: 'Bungoma' },
  'Waluch Bungoma Station Mwalimu House': { town: 'Bungoma', county: 'Bungoma' },
  'Jumia Fortify Bomet Station': { town: 'Bomet', county: 'Bomet' },
  'Jumia Fortify Sotik Station': { town: 'Sotik', county: 'Bomet' },
  'G4S Eldama Ravine Station': { town: 'Eldama Ravine', county: 'Baringo' },
  'G4S Kabarnet Station': { town: 'Kabarnet', county: 'Baringo' },
  'Jumia G4S Marigat Station': { town: 'Marigat', county: 'Baringo' },
  'Cossim Eldoret Station': { town: 'Eldoret', county: 'Uasin Gishu' },
  'Flexcom Eldoret Station': { town: 'Eldoret', county: 'Uasin Gishu' },
  'Jumia Kebian Soy Station': { town: 'Soy', county: 'Uasin Gishu' },
  'Kebian Eldoret Station': { town: 'Eldoret', county: 'Uasin Gishu' },
  'Jumia Kebian Eldoret_Uganda St Station': { town: 'Eldoret', county: 'Uasin Gishu' },
  'KE-3PL-Kebian Moi University-Station': { town: 'Moi University', county: 'Uasin Gishu' },
  'Jumia Kebian Pickup Station at Soy': { town: 'Soy', county: 'Uasin Gishu' },
  'Jumia Lakeland South B Station': { town: 'South B', county: 'Nairobi' },
  'Kloss Buruburu Station': { town: 'Buruburu', county: 'Nairobi' },
  'Jumia PickUp Station at Adams Arcade': { town: 'Adams Arcade', county: 'Nairobi' },
  'Jumia Kloss Dagoretti Station': { town: 'Dagoretti', county: 'Nairobi' },
  'Jumia Kloss Ronald Ngala Station': { town: 'Ronald Ngala (CBD)', county: 'Nairobi' },
  'Kloss CBD Station': { town: 'Nairobi CBD', county: 'Nairobi' },
  'Lakeland CBD Station': { town: 'Nairobi CBD', county: 'Nairobi' },
  'Jumia CBD Kantaria Station': { town: 'Nairobi CBD', county: 'Nairobi' },
  'Cossim Fedha Station': { town: 'Fedha', county: 'Nairobi' },
  'Kloss Fedha Station': { town: 'Fedha', county: 'Nairobi' },
  'Jumia Warehouse Station': { town: null, county: null },
  'Cossim Shujaa Mall Station': { town: 'Umoja', county: 'Nairobi' },
  'JBN Express Utawala Station': { town: 'Utawala', county: 'Nairobi' },
  'Kloss Transami Station': { town: 'Industrial Area', county: 'Nairobi' },
  'Jumia Lakeland Mombasa rd Station': { town: 'Mombasa Road', county: 'Nairobi' },
  'Jumia JBN Roasters -Station': { town: 'Roasters', county: 'Nairobi' },
  'Cossim Githurai Station': { town: 'Githurai', county: 'Nairobi' },
  'Kloss Kahawa Sukari Station': { town: 'Kahawa Sukari', county: 'Nairobi' },
  'Kloss Huruma Pickup Station': { town: 'Huruma', county: 'Nairobi' },
  'Kloss Imara Daima Station': { town: 'Imara Daima', county: 'Nairobi' },
  'Lakeland Kahawa Wedani Station': { town: 'Kahawa Wendani', county: 'Kiambu' },
  'Cossim Kahawa West Station': { town: 'Kahawa West', county: 'Nairobi' },
  'Jumia Denfa Eastleigh Station': { town: 'Eastleigh', county: 'Nairobi' },
  'Jumia JBN Express Kamulu Station': { town: 'Kamulu', county: 'Nairobi' },
  'Jumia The Hub Karen Station': { town: 'Karen', county: 'Nairobi' },
  'Jumia EBEE MOBILITY Kilimani Station': { town: 'Kilimani', county: 'Nairobi' },
  'Cossim Kasarani PUS': { town: 'Kasarani', county: 'Nairobi' },
  'TRD Santon Station': { town: null, county: null },
  'Kloss Langata Station': { town: "Lang'ata", county: 'Nairobi' },
  'Jumia Fortify Naivasha Road/Riruta Station': { town: 'Riruta', county: 'Nairobi' },
  'Kloss Highrise Station': { town: 'Highrise', county: 'Nairobi' },
  'Jumia Cossim Roysambu Station': { town: 'Roysambu', county: 'Nairobi' },
  'TRD Zimmerman Station': { town: 'Zimmerman', county: 'Nairobi' },
  'Jumia JBN Express Ruai Station': { town: 'Ruai', county: 'Nairobi' },
  'JBN Express Ruaraka Station': { town: 'Ruaraka', county: 'Nairobi' },
  'Jumia JBN Express Babadogo Station': { town: 'Baba Dogo', county: 'Nairobi' },
  'Kloss Mathare Station': { town: 'Mathare', county: 'Nairobi' },
  'JBN Express Pangani Station': { town: 'Pangani', county: 'Nairobi' },
  'Cossim Mtindwa Station': { town: 'Mutindwa (Buruburu)', county: 'Nairobi' },
  'Kloss Umoja Station': { town: 'Umoja', county: 'Nairobi' },
  'Jumia Kloss Westlands Station': { town: 'Westlands', county: 'Nairobi' },
  'Jumia Lakeland Komarock Station': { town: 'Komarock', county: 'Nairobi' },
  'G4S Gatundu Town Station': { town: 'Gatundu', county: 'Kiambu' },
  'Lakoches Githunguri Station': { town: 'Githunguri', county: 'Kiambu' },
  'JBN Express Juja-Station': { town: 'Juja', county: 'Kiambu' },
  'Jumia Cossim Witeithie Station': { town: 'Witeithie', county: 'Kiambu' },
  'JUMIA TRD KIAMBU Station': { town: 'Kiambu', county: 'Kiambu' },
  'Jumia Kiambu Station': { town: 'Kiambu', county: 'Kiambu' },
  'Lakoches Kikuyu Station': { town: 'Kikuyu', county: 'Kiambu' },
  'JBN Express Kinoo Station': { town: 'Kinoo', county: 'Kiambu' },
  'Lakoches Limuru Station': { town: 'Limuru', county: 'Kiambu' },
  'Jumia Ruaka Station': { town: 'Ruaka', county: 'Kiambu' },
  'Lakoches Ruiru Station': { town: 'Ruiru', county: 'Kiambu' },
  'TRD Kimbo Station': { town: 'Kimbo', county: 'Kiambu' },
  'Jumia Ruiru Station': { town: 'Ruiru', county: 'Kiambu' },
  'Cossim Thika - Makongeni': { town: 'Thika', county: 'Kiambu' },
  'Cossim Thika Arcade Station': { town: 'Thika', county: 'Kiambu' },
  'JBN Express Thika Station': { town: 'Thika', county: 'Kiambu' },
  'Jumia JBN Thindigua Station': { town: 'Thindigua', county: 'Kiambu' },
  'Jumia Lakoches Wangige Station': { town: 'Wangige', county: 'Kiambu' },
  'Jumia Lakoches Isinya Station': { town: 'Isinya', county: 'Kajiado' },
  'Jumia Lakoches Kajiado Station': { town: 'Kajiado', county: 'Kajiado' },
  'Fortify Kiserian Station': { town: 'Kiserian', county: 'Kajiado' },
  'Lakeland Kitengela Station': { town: 'Kitengela', county: 'Kajiado' },
  'Lakoches Enterprises': { town: null, county: null },
  'Jumia Skyveshop Loitoktok Station': { town: 'Loitoktok', county: 'Kajiado' },
  'Fortify Solutions': { town: null, county: null },
  'Kloss Rongai Pickup Station': { town: 'Ongata Rongai', county: 'Kajiado' },
  'Cossim Ongata Rongai Station': { town: 'Ongata Rongai', county: 'Kajiado' },
  'Jumia Cossim Awasi Station': { town: 'Awasi', county: 'Kisumu' },
  'Jumia Lakeland Kisumu Mega City Station': { town: 'Kisumu', county: 'Kisumu' },
  'Flexcom Kisumu Station': { town: 'Kisumu', county: 'Kisumu' },
  'Lakeland Kisumu Station': { town: 'Kisumu', county: 'Kisumu' },
  'Cossim Maseno Station': { town: 'Maseno', county: 'Kisumu' },
  'Jumia Cossim Gilgil Station': { town: 'Gilgil', county: 'Nakuru' },
  'Fortify Barnabas station': { town: null, county: null },
  'Jumia Fortify Molo Station': { town: 'Molo', county: 'Nakuru' },
  'Cossim Naivasha Station': { town: 'Naivasha', county: 'Nakuru' },
  'Flexcom Vikers House Station': { town: 'Nakuru', county: 'Nakuru' },
  'Cossim Nakuru Station': { town: 'Nakuru', county: 'Nakuru' },
  'Jumia Nakuru': { town: 'Nakuru', county: 'Nakuru' },
  '3PL-Fortify Njoro-Station': { town: 'Njoro', county: 'Nakuru' },
  'Flexcom Changamwe Station': { town: 'Changamwe', county: 'Mombasa' },
  'Flexcom Mikindani Station': { town: 'Mikindani', county: 'Mombasa' },
  'Jumia Ganjoni Station': { town: 'Ganjoni', county: 'Mombasa' },
  'Flexcom Kisauni Station': { town: 'Kisauni', county: 'Mombasa' },
  'Skyveshop Kongowea Station': { town: 'Kongowea', county: 'Mombasa' },
  'Skyveshop Likoni Station': { town: 'Likoni', county: 'Mombasa' },
  'Jumia BeeJohns Migadini Station': { town: 'Migadini', county: 'Mombasa' },
  'Jumia BeeJohns Miritini Station': { town: 'Miritini', county: 'Mombasa' },
  'Skyveshop Mshomoroni Station': { town: 'Mshomoroni', county: 'Mombasa' },
  'Flexcom Mombasa Station': { town: 'Mombasa', county: 'Mombasa' },
  'Jumia Mombasa': { town: 'Mombasa', county: 'Mombasa' },
  'Jumia Skyve Station': { town: null, county: null },
  'Skyveshop Tudor Station': { town: 'Tudor', county: 'Mombasa' },
  'Flexcom Nyali Station': { town: 'Nyali', county: 'Mombasa' },
  'Jumia Mtwapa Station': { town: 'Mtwapa', county: 'Kilifi' },
  'Jumia Lakeland Kondele Station': { town: 'Kondele', county: 'Kisumu' },
  'Jumia Amison Busia Station': { town: 'Busia', county: 'Busia' },
  'KE-3PL-Skyveshop Mutomo-Station': { town: 'Mutomo', county: 'Kitui' },
};

export function deriveGeography(stationName) {
  return STATION_GEOGRAPHY[stationName] ?? { town: null, county: null };
}
